version: '3.8'

services:
  trainer:
    build: .
    container_name: mlops_trainer
    entrypoint: ["python", "model.py"]
    depends_on:
      - mlflow
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - DOCKER_CONTAINER=true  # Add this line
    volumes:
      - ./app:/app  # Mount the ./app directory into /app
      - ./models:/models
      - ./data:/app/data
    networks:
      - mlops_network

  api:
    build: .
    container_name: mlops_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    depends_on:
      - prometheus
      - trainer
    volumes:
      - ./app:/app
      - ./models:/models
      - ./data:/app/data
    networks:
      - mlops_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./dashboards/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./dashboards/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    networks:
      - mlops_network

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./dashboards/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - mlops_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./dashboards/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./dashboards/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - mlops_network

  mlflow:
    image: python:3.9-slim
    container_name: mlflow
    command: >
      sh -c "pip install mlflow==2.2.1 boto3==1.24.89 && mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root s3://irisbucketmlops/mlflow/ --host 0.0.0.0 --port 5000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    env_file:
      - .env
    volumes:
      - ./mlflow_data:/mlflow
    ports:
      - "5000:5000"
    networks:
      - mlops_network

networks:
  mlops_network:
    driver: bridge
