stages:
  train:
    cmd: /Users/juliencardi/Documents/ing3/mlops/mlops_project/mlops-api-predictor/myenv/bin/python app/model.py
    deps:
      - data/raw/iris.csv
      - app/model.py
    outs:
      - models/model.joblib
    params:
      - train
