name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full git history is fetched for DVC

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install DVC and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc[s3]  # Install DVC with S3 support
        pip install -r requirements.txt  # Install other project dependencies

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region $AWS_DEFAULT_REGION

    - name: Pull data with DVC
      run: dvc pull

    - name: Verify DVC pull
      run: ls -la models/

    - name: Run tests
      run: pytest tests

    - name: Clean up
      run: rm -rf models/
